<?php
/**
 *
 */
 require APPPATH . 'libraries/REST_Controller.php';
 require APPPATH . 'libraries/Format.php';
 require APPPATH . 'libraries/curl.php';
 use Restserver\Libraries\REST_Controller;
class test extends REST_Controller
{

  function index_get()
  {
    // code...
    $message = [
        'id' => 100, // Automatically generated by the model
        'name' => $this->post('name'),
        'email' => $this->post('email'),
        'message' => 'Added a resource'
    ];
    $this->session->set_userdata('id','hahahaha');
    $this->response($message,REST_Controller::HTTP_CREATED);
  }
  function hai_get(){
    $message = [
        'message' => 'curl done'
    ];
    $this->response($message,REST_Controller::HTTP_CREATED);
  }
  function hei_get(){
    // code...
    if(empty($this->session->userdata())){
      $message = [
          'id' => 100, // Automatically generated by the model
          'name' => $this->session->userdata(),
          'email' => $this->get('email'),
          'message' => 'kkosong'
      ];
    }else{
      $message = [
          'id' => 100, // Automatically generated by the model
          'name' => $this->session->userdata(),
          'email' => $this->get('email'),
          'message' => 'Added a resource'
      ];
    }

    $this->set_response($message); // CREATED (201) being the HTTP response code
  }
}

 ?>
